### Successful Responses

### Retrieve All Alcohol from Alcohol Table

GET http://localhost:3000/api/mixers


### Add new Alcohol

POST http://localhost:3000/api/mixers
Content-Type: application/json
# Use the User http client to log in with a user, then get the jwt tokent and paste it here in the format of "Bearer <jwt token>"
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDM3NzAyNDMsInN1YiI6NH0.lwLSg0MZRVl4GbpV4Vp2vldSxcW-NvzKg5ynQIgG5vo

{
    "name":"Pepsi2",
    "volume_in_ml": 4000,
    "critical_volume":2000

}

### Show
GET http://localhost:3000/api/mixers/:id
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDMxNzA5MTYsInN1YiI6NH0.gmFtrrtPLYHkLzfj0YSp_KlXOyywaS66tnT2oxbIA0E

{
    "name":"Pepsi"
}


### Edit an Existing Alcohol

PUT http://localhost:3000/api/mixers/12
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDM3NzAyNDMsInN1YiI6NH0.lwLSg0MZRVl4GbpV4Vp2vldSxcW-NvzKg5ynQIgG5vo

{
    "name":"Jim Beam",
    "volume_in_ml": 4000,
    "critical_volume":2000

}

### DELETE>destroy
DELETE http://localhost:3000/api/mixers/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDMxNzA5MTYsInN1YiI6NH0.gmFtrrtPLYHkLzfj0YSp_KlXOyywaS66tnT2oxbIA0E